### ISSUE TITLE
 flatpak-managed-install.service sometimes fails to start

### ISSUE THREAD

**Issue by shyuen** [gmodena/nix-flatpak#97] opened 2024-11-21 17:11 UTC
When I do a `nixos-rebuild switch`, it will occasionally fail to start the `flatpak-managed-install.service`. 
```
× flatpak-managed-install.service
     Loaded: loaded (/etc/systemd/system/flatpak-managed-install.service; enabled; preset: ignored)
     Active: failed (Result: exit-code) since Thu 2024-11-21 10:00:19 MST; 4s ago
 Invocation: c074468deb5649b3843e8c7336c10326
    Process: 34144 ExecStart=/nix/store/85cbl69mqs8zi927kviwzpbclhn6n2an-flatpak-managed-install (code=exited, status=1/FAILURE)
   Main PID: 34144 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
         IO: 7.3M read, 0B written
   Mem peak: 11.1M
        CPU: 45ms

Nov 21 10:00:19 nixos systemd[1]: Starting flatpak-managed-install.service...
Nov 21 10:00:19 nixos 85cbl69mqs8zi927kviwzpbclhn6n2an-flatpak-managed-install[34154]: error: Can't load uri https://dl.flathub.org/repo/flathub.flatpakrepo: While fetching https://dl.flathub.org/repo/flathub.flatpakrepo: [6] Could not resolve hostname
Nov 21 10:00:19 nixos systemd[1]: flatpak-managed-install.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 10:00:19 nixos systemd[1]: flatpak-managed-install.service: Failed with result 'exit-code'.
Nov 21 10:00:19 nixos systemd[1]: Failed to start flatpak-managed-install.service.
Nov 21 10:00:19 nixos systemd[1]: flatpak-managed-install.service: Consumed 45ms CPU time, 11.1M memory peak, 7.3M read from disk.
warning: error(s) occurred while switching to the new configuration
```

I can run the rebuild switch command again and it will usually work the 2nd time so it's not a big issue, but I'm wondering if there's a way to avoid this occasional error.

**Comment by gmodena** [comment] 2024-11-22 13:31
Hi @shyuen ,

Thanks for reaching out. This issue looks like a duplicate of #45. Could have a look at the workarounds proposed in that thread, and eventually follow up to the discussion there?

**Closed by gmodena** 2024-11-22 13:31 UTC
